# Generated by Django 4.0.3 on 2022-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to='events/')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('published_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to='news/')),
                ('description', models.TextField()),
                ('published_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
