# Generated by Django 4.0.3 on 2022-04-26 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30), django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
