# Generated by Django 4.0.3 on 2022-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='universityuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='universityuser',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=7),
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
