# Generated by Django 4.0.3 on 2022-04-10 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_universityuser_is_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('quizzes', models.ManyToManyField(related_name='created_quizzes', to='classroom.quiz')),
                ('specialization', models.ManyToManyField(related_name='teachers_specialization', to='classroom.subject')),
            ],
        ),
    ]
