# Generated by Django 4.0.3 on 2022-04-25 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_admin_alter_quiz_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(5, message='Your First Name must be at least 3 symbols')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(5, message='Your Last Name must be at least 5 symbols')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_images'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(5, message='Your First Name must be at least 3 symbols')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(5, message='Your Last Name must be at least 5 symbols')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_images'),
        ),
    ]
