# Generated by Django 4.0.3 on 2022-04-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_remove_admin_user_remove_teacher_specialization_and_more'),
        ('web', '0004_event_organizer_alter_news_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
