# Generated by Django 4.0.3 on 2022-04-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_alter_teacher_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
    ]
