# Generated by Django 4.0.3 on 2022-04-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_faculty_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
